apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      serviceAccountName: k8s-service-account
      containers:
        - name: user-api
          image: ${_REGISTRY_URL}/${PROJECT_ID}/${_REPOSITORY_NAME}/user-api:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-password
            - name: REDIS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_HOSTNAME
            - name: NOTIFICATION_API_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NOTIFICATION_API_HOSTNAME
            - name: OPENAPI_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CLIENT_ADDRESS
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 768Mi
            limits:
              cpu: 300m
              memory: 1024Mi
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          args:
            - "--port=5432"
            - "$(DB_INSTANCE_NAME)"
          env:
            - name: DB_INSTANCE_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_INSTANCE_NAME
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi