server:
  port: 8081

# Application specific configs
photomap:
  security:
    secret: ${JWT_SECRET:photomap-secret}
  client:
    url: ${PHOTOMAP_CLIENT_URL:http://localhost:5173}

# API Services configuration
api:
  user:
    host: ${USER_API_HOSTNAME:localhost}
    port: ${USER_API_PORT:8082}
  photo:
    host: ${PHOTO_API_HOSTNAME:localhost}
    port: ${PHOTO_API_PORT:8083}
  geojson:
    host: ${GEOJSON_GENERATOR_HOSTNAME:localhost}
    port: ${GEOJSON_GENERATOR_PORT:8088}
  notification:
    host: ${NOTIFICATION_API_HOSTNAME:localhost}
    port: ${NOTIFICATION_API_PORT:8084}

# Spring configurations
spring:
  cloud:
    gateway:
      httpclient:
        pool:
          type: disabled
      default-filters:
        - name: Retry
          args:
            methods: GET,PUT,POST,DELETE,PATCH
            exceptions:
              - reactor.netty.http.client.PrematureCloseException
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${photomap.client.url}
            allowedHeaders: "*"
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS, PATCH]
            allowCredentials: true

  # Database configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/photomap}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:Password123}

  # Redis configuration
  data:
    redis:
      host: ${REDIS_HOSTNAME:localhost}
      port: 6379

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: [health, liveness, readiness, info]
  endpoint:
    health:
      probes:
        enabled: true

# Logging configuration
logging:
  filter:
    enabled: true
  level:
    ua.in.photomap: INFO
    org.springframework:
      cache: INFO
      data.redis: INFO
      cloud.gateway.filter: INFO

# API Documentation
springdoc:
  api-docs:
    enabled: true
    path: /doc/api-gateway/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /doc/api-gateway/v3/api-docs/swagger-config
    urls:
      - url: /doc/photo-api/v3/api-docs
        name: photo-api
      - url: /doc/user-api/v3/api-docs
        name: user-api
      - url: /doc/notification-api/v3/api-docs
        name: notification-api
      - url: /doc/geojson-generator/v3/api-docs
        name: geojson-generator

# Swagger security
swagger:
  security:
    username: ${SWAGGER_USERNAME}
    password: ${SWAGGER_PASSWORD}