apiVersion: v1
kind: Service
metadata:
  name: notification-api-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"8084":"notification-api-backend-config"}}'
spec:
  selector:
    app: notification-api
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084