---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: photomap-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: root-scram-credentials
    - name: photomapUser
      db: photomap
      passwordSecretRef:
        name: mongodb-secret
        key: photomapPassword
      roles:
        - name: readWrite
          db: photomap
      scramCredentialsSecretName: photomapuser-scram-credentials
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib