apiVersion: v1
kind: Service
metadata:
  name: geojson-generator-service
spec:
  selector:
    app: geojson-generator
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
