apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  annotations:
#    cloud.google.com/backend-config: '{"ports": {"80":"photomap-api-gateway-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081