version: '3.1'

services:
  photomap-ui:
    image: photomap-nuxt-ui:latest
    ports:
      - "5173:8080"
    environment:
      NUXT_PUBLIC_GOOGLE_CLIENT_ID: ${NUXT_PUBLIC_GOOGLE_CLIENT_ID}
      NUXT_PUBLIC_BASE_API_URL: ${NUXT_PUBLIC_BASE_API_URL}
      NUXT_PUBLIC_BROWSER_BASE_API_URL: ${NUXT_PUBLIC_BROWSER_BASE_API_URL}
      NUXT_PUBLIC_CLUSTER_API_URL: ${NUXT_PUBLIC_CLUSTER_API_URL}
      NUXT_PUBLIC_TIMEOUT: ${NUXT_PUBLIC_TIMEOUT}
      NUXT_PUBLIC_WS_URL: ${NUXT_PUBLIC_WS_URL}
      NUXT_PUBLIC_NODE_ENV: ${NUXT_PUBLIC_NODE_ENV}
      NUXT_PUBLIC_CLIENT_URL: ${NUXT_PUBLIC_CLIENT_URL}
      NUXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NUXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      NUXT_PUBLIC_MAPTILER_API_KEY: ${NUXT_PUBLIC_MAPTILER_API_KEY}
    networks:
      - photomap
    restart: always

networks:
  photomap: